spring:
  application:
    name: marketdata
  cloud: # GCP
    gcp:
      project-id: melodic-ranger-479719-m8
  config:
    import: "sm://" # GCP Secret Manager
  kafka: # Kafka
    bootstrap-servers: ${sm://KAFKA_BOOTSTRAP_SERVERS_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  coinmarketcap:
    api-key: ${sm://COINMARKETCAP_API_KEY}
    header-name: "X-CMC_PRO_API_KEY"
    base-url: "https://sandbox-api.coinmarketcap.com"
    endpoint-crypto-listings: "v1/cryptocurrency/listings/latest"
  marketdata:
    poll-interval-ms: 5000
